### ISSUE TITLE
The test.json File,should we access it?

### ISSUE THREAD

**Issue by xiaochangg** [spring-cloud-samples/config-repo#7]

**Comment by spencergibb** [comment]
Your question is unclear, can you please elaborate?

**Comment by xiaochangg** [comment]
OK ,my question:
I hope you can help me。my question：
1.If the Git repository file is the .json suffix (as test.json)，not .yml or .properties suffix. The spring cloud config server can be accessed through the url (http://localhost:8888/application/default/master/test.json),
But How should the spring cloud config client access the spring cloud config server to get the test.json file content ?  How do you use code access?
2. How should a spring cloud config client access the Multiple Files（.json suffix）? 
 Thank you very much

**Comment by spencergibb** [comment]
There is no automated access. You have the url and `RestTemplate`.
